### ISSUE TITLE
Possible Bug - normalizeRAVEL output

### ISSUE THREAD

**Issue by martapadrela** [Jfortin1/RAVEL#13]
Hello,

I am normalizing MRI images of glioma patients using several methods. I have noticed that the output matrix of normalized images is exactly the same using the RAVEL and White Stripe method. Although the actual normalized images are different.

Looking deeper into the code, I think I have found a small bug in the normalizeRAVEL function, specifically in the final lines, where it reads:
`if (returnMatrix) {
    return(V)
  }`
Shouldn't it be?
`if (returnMatrix) {
    return(V.norm)
  }`

Thanks for your help!

**Comment by muschellij2** [comment]
Yes, I think that's correct.

**Comment by Jfortin1** [comment]
Indeed, just push a fix, thanks @martapadrela

**Comment by martapadrela** [comment]
Thank you for solving this so quickly!
