### ISSUE TITLE
normalizeRAVEL: Could not find function ".write_brain"

### ISSUE THREAD

**Issue by paul-reiners** [Jfortin1/RAVEL#15]
I am using the [normalizeRavel][1] function.

I have the following R code:

    library(pbapply)
    library(neurobase)
    
    source("./normalizeRAVEL.R")
    
    dir = "/users/9/reine097/data/fairview-ag/anonymized/4_processed/"
    input.files  <- list.files(dir, full.names=TRUE)
    brain.mask <- "/users/9/reine097/mni_icbm152_t1_tal_nlin_sym_09a_mask_int16.nii.gz" 
    # Confirm the input arguments match the expected format and data types for the normalizeRAVEL function.
    control.mask <- "/users/9/reine097/data/fairview-ag/anonymized/6_control_mask/control_mask_08.nii.gz"
    check_nifti(brain.mask)
    check_nifti(control.mask)
    tryCatch({
      normalizeRAVEL(input.files, brain.mask = brain.mask, control.mask = control.mask, k=1, writeToDisk=TRUE, WhiteStripe=FALSE)
    }, error = function(e) {
      message("Error: ", e)
    })

I am getting the following error:

    Error: Error in .write_brain(brain.norm = V.norm[, i], output.file = output.files[i], : could not find function ".write_brain"

Does this means I am missing a [Neuroconductor package][3]? However, I have no idea which one is the correct one or if that is indeed the problem.

Any ideas?

  [1]: https://github.com/Jfortin1/RAVEL?tab=readme-ov-file#35-ravel-normalization
  [2]: https://github.com/Jfortin1/RAVEL
  [3]: https://neuroconductor.org/list-packages/all

**Comment by paul-reiners** [comment]
Add the line source("./utils.R").

**Comment by muschellij2** [comment]
I would recommend installing the package and using the functions like that rather than sourcing.

**Comment by paul-reiners** [comment]
You're probably right.  I don't know why I don't do that more often.
