### ISSUE TITLE
RAVEL normalisation in subject space

### ISSUE THREAD

**Issue by tetrille** [Jfortin1/RAVEL#9]
Hello,

I'm performing RAVEL normalisation of T1- and T2-weighted images following the README.md, but this involves non-linear registration to a template and I need the output in the original subject space. 

It's possible to back-transform the RAVEL normalised images to the subject space using antsApplyTransforms, but this leads to multiple transformations with ensuing interpolations. Is there any way to perform the RAVEL normalisation directly in the subject space?

**Comment by muschellij2** [comment]
One of the crucial elements of RAVEL is that each row of the matrix decomposed means the "same thing", in this case it refers to spatial area.  Technically, it could be possible to do this, but we haven't implemented it.   

I don't understand 
> this leads to multiple transformations with ensuing interpolations
There is one (composed) transformation that is affine+SyN with an interpolation to the template and RAVEL is applied.  After RAVEL is applied, that reverse transformation+ interpolation can be applied and the data is transformed back into native space.  Though there is technically 2 transformations and interpolations, I see it as only the back transform that's really done, depending on your point of view.

Above, I could see you "technically doing"
1) Get overlap CSF mask in template space
2) Back transform mask to native space for all patients, get nearest voxel for each voxel (**may have some duplicates in this data**)
3) Gather the data into a matrix and RAVEL.

I'm a little hesitant to suggest this, however.  An implementation of RAVEL (https://github.com/jcreinhold/intensity-normalization) also requires registration https://intensity-normalization.readthedocs.io/en/latest/normalization.html#module-intensity_normalization.normalize.ravel

**Comment by Jfortin1** [comment]
RAVEL, **as described in the paper**, necessarily requires the voxels to be aligned to a common space since it fits voxel-wise linear regression models; there is no way to get around this. To get the normalized values in native space, as @muschellij2 mentioned, just apply the back-transformation. This does not come at an additional cost.
